### ISSUE TITLE
Interesting keyword identification framework

### ISSUE THREAD

**Issue by messamat** [albertlarson/eflows#1]
https://onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13268

**Comment by albertlarson** [comment]
thanks for this

edit:
@messamat i just added you as a collaborator and enabled discussions #2. i'm wondering if that might be a good place to pass through articles and talk there? i think it might be a better avenue because of the connotation of a problem existing associated with the word "issues" as opposed to the connotations associated with "discussions". it seems like a good place if we wanted others to be able to get involved?
